### ISSUE TITLE
Provider or Endpoint URL disambiguation

### ISSUE THREAD

**Issue by sambacha** [manifoldfinance/wallet_switchNetworkRpcProvider#5]
Right now the spec is blurring the lines between a `provider` and reconfiguring the wallet's RPC endpoint url. We should clarify this usage 

- specify that its effecting the Endpoint URL
- separately discuss what a Provider like this would look like (eg. Ethers InfuraProvider nodejs package, etc)

**Comment by zimbatm** [comment]
Not doing this
